### PR TITLE
fix: do not import typescript outside of config/project loading

### LINKED ISSUE #1426: `Cannot find module 'typescript'` when using `npx ts-node`
We have been using `npx ts-node` to run a specific script for quite some while now, and with update 10.2.0 that script started to fail.

### Expected Behavior

Script works.

### Actual Behavior

```
Cannot find module 'typescript'
Require stack:
- /home/runner/.npm/_npx/2763/lib/node_modules/ts-node/dist/index.js
- /home/runner/.npm/_npx/2763/lib/node_modules/ts-node/dist/repl.js
- /home/runner/.npm/_npx/2763/lib/node_modules/ts-node/dist/bin.js
```

### Steps to reproduce the problem

https://github.com/prisma/e2e-tests/pull/1982

### Minimal reproduction

-

### Specifications

* ts-node version: 10.2.0
* node version: 12.22.4
* TypeScript version: -
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "lib": ["ESNext", "dom"]
  }
}
```
* Operating system and version: Ubuntu 20.04.2 LTS (GH Actions)
* If Windows, are you using WSL or WSL2?:

### PR DESCRIPTION
**Pull request by Songkeys**
EDIT from @cspotcode to track related issues: Looks like this fixes a bug introduced by #1383. Should resolve #1426, #1427, #1428.

---

Or: to resolve typescript module correctly.

The current code still has a "hard" top-level requiring for typescript, which may cause issues when installing ts-node globally and installing typescript locally (i.e. you have to install them both globally or both locally). Since we've already resolving typescript smartly in the code using `loadCompiler`, why not accessing `ScriptTarget` from the resolved one?

### CODE REVIEW

**Comment by cspotcode** [comment]
Thanks, good catch.  Looks like this fixes a bug introduced by #1383.  Should resolve #1426, #1427, #1428.
