### ISSUE TITLE
ts-node doesn't work with latest typescript 2.5 

### ISSUE THREAD

**Issue by cevek** [TypeStrong/ts-node#360]
`ts-node 1.tsx`
```
TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'react'. (2688)
1.tsx (1,24): Cannot find module 'react'. (2307)
```

`tsc` works without problems

**Comment by cevek** [comment]
create file `1.tsx`
```ts
import * as React from 'react';
<div className="foo"></div>
```
create file `tsconfig.json`

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "jsx": "react"
  }
}
```

```
npm i -g ts-node
npm i -g typescript@next
npm init -y
npm i @types/react 
ts-node 1.tsx
```

And result is 
```
/usr/local/lib/node_modules/ts-node/src/index.ts:300
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'react'. (2688)
1.tsx (1,24): Cannot find module 'react'. (2307)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:300:15)

```

**Comment by cevek** [comment]
with typescript@2.4 works correctly

**Comment by cevek** [comment]
I think its related to this merge https://github.com/Microsoft/TypeScript/pull/12336

**Comment by blakeembrey** [comment]
Thanks for this! I'll have to look next week, but until then feel free to investigate yourself and/or submit a PR.

**Comment by cevek** [comment]
Bug on the typescript side https://github.com/Microsoft/TypeScript/issues/16616

**Comment by cevek** [comment]
PR https://github.com/TypeStrong/ts-node/pull/366

**Comment by blakeembrey** [comment]
Closed with https://github.com/TypeStrong/ts-node/pull/366, cheers!
