### ISSUE TITLE
New TS errors after updating to v6.0.0

### ISSUE THREAD

**Issue by stoic-dev** [TypeStrong/ts-node#573]
Since I updated, I have been getting a lot of new TS errors that I haven't gotten before. When I run my tests in v5.0.1 they all pass and everything runs fine.

```
  Default
    ✓ should throw InvalidArgumentException if value does not match property type
    ✓ should attach a DefaultAnnotation to the decorated property
    ✓ should return the specified default value if initial value is null or undefined

  Description
    ✓ should attach a DescriptionAnnotation to the decorated properties

  Entity
    ✓ should attach an EntityAnnotation to the decorated class

  AcceptValidator
    ✓ should throw an InvalidArgumentException if it is not constructed with an array
    ✓ should throw an InvalidArgumentException if it is constructed with an empty array
    ✓ should fail validation if the passed in value is not in the accepted values array
    ✓ should pass validation if the passed in value is in the accepted values array

  Accept
    ✓ should attach an AcceptValidator to the decorated properties metadata

  ElementTypeValidator
    ✓ should should throw an InvalidArgumentException if a function is not passed in to constructor
    ✓ should should throw an InvalidArgumentException if the value to validate is not an Array
    ✓ should fail validation if the type of value does not match the type with which the validator was constructed
    ✓ should fail validation when value is a primitive and does not match the type with which the validator was constructed
    ✓ should pass validation if the type of value does match the type with which the validator was constructed
    ✓ should pass validation when value is a primitive and does match the type with which the validator was constructed

  ElementType
    ✓ should throw an UnsupportedOperationException if the decorated property is not an Array type
    ✓ should attach an ElementTypeValidator to the decorated property's metadata

  RequiredValidator
    ✓ should fail validation if value is null or undefined
    ✓ should pass validation if value is not null and not undefined

  Required
    ✓ should attach a RequiredValidator to the decorated property's metadata

  TypeValidator
    ✓ should should throw an InvalidArgumentException if a function is not passed in to constructor
    ✓ should fail validation if the type of value does not match the type with which the validator was constructed
    ✓ should fail validation when value is a primitive and does not match the type with which the validator was constructed
    ✓ should pass validation if the type of value does match the type with which the validator was constructed
    ✓ should pass validation when value is a primitive of the type with which the validator was constructed
    ✓ should return true if value is null or undefined

  Type
    ✓ should attach a TypeValidator to the decorated property's metadata

  validateEntity
    ✓ should run validators on entity
    ✓ should run validators on any nested entities
    ✓ should throw an error for each validator that fails
    ✓ should throw errors for all nested validators at once

  setClassProperties
    ✓ should throw an InvalidArgumentException if passed null or undefined for the properties argument
    ✓ should throw an InvalidArgumentException if passed null or undefined for the classPrototype argument
    ✓ should assign passed in properties to the passed in class prototype
```
Here are the results when I run it with v6.0.0

```
TSError: ⨯ Unable to compile TypeScript
src/metadata/annotation/default-annotation/default-annotation.spec.ts (35,17): Parameter 'exception' implicitly has an 'any' type. (7006)
src/metadata/annotation/default-annotation/default-annotation.spec.ts (59,31): Element implicitly has an 'any' type because type '{}' has no index signature. (7017)
    at getOutput (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:329:15)
    at Object.compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:515:11)
    at Module.m._compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:402:43)
    at module.exports (/home/john/code/magellan-collections/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:405:12)
    at /home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:405:12)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /home/john/code/magellan-collections/node_modules/mocha/lib/mocha.js:253:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/john/code/magellan-collections/node_modules/mocha/lib/mocha.js:250:14)
    at Mocha.run (/home/john/code/magellan-collections/node_modules/mocha/lib/mocha.js:577:10)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/mocha/bin/_mocha:591:18)
    at Module._compile (module.js:660:30)
    at Module.replacementCompile (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/john/code/magellan-collections/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at runMain (/home/john/.node-spawn-wrap-14751-4772e3a9bdc9/node:68:10)
    at Function.<anonymous> (/home/john/.node-spawn-wrap-14751-4772e3a9bdc9/node:171:5)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at /home/john/.node-spawn-wrap-14751-4772e3a9bdc9/node:178:8
    at Object.<anonymous> (/home/john/.node-spawn-wrap-14751-4772e3a9bdc9/node:181:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```
I did try to fix those specific errors but when I do, I just get more and on things that are definitely typed. In order to just try to get around the implicit any errors, I just disabled that check in my `tsconfig.json`. That takes care of the implicit any errors, but that just results in one that makes even less sense.

```
TSError: ⨯ Unable to compile TypeScript
src/exceptions/exception.ts (5,14): Property 'message' does not exist on type 'Exception'. (2339)
src/exceptions/exception.ts (6,14): Property 'name' does not exist on type 'Exception'. (2339)
    at getOutput (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:329:15)
    at Object.compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:515:11)
    at Module.m._compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:402:43)
    at Module.m._compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:402:23)
    at module.exports (/home/john/code/magellan-collections/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:405:12)
    at /home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:405:12)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/john/code/magellan-collections/src/exceptions/invalid-argument-exception.ts:1:1828)
    at Module._compile (module.js:660:30)
    at Module.replacementCompile (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:402:23)
    at Module.m._compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:402:23)
    at module.exports (/home/john/code/magellan-collections/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:405:12)
    at /home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:405:12)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/john/code/magellan-collections/src/exceptions/exceptions.index.ts:1:1189)
    at Module._compile (module.js:660:30)
    at Module.replacementCompile (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:402:23)
    at Module.m._compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:402:23)
    at module.exports (/home/john/code/magellan-collections/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:405:12)
    at /home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:405:12)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/john/code/magellan-collections/src/metadata/annotation/default-annotation/default-annotation.spec.ts:4:1)
    at Module._compile (module.js:660:30)
    at Module.replacementCompile (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.m._compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:402:23)
    at Module.m._compile (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:402:23)
    at module.exports (/home/john/code/magellan-collections/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:405:12)
    at /home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/john/code/magellan-collections/node_modules/ts-node/src/index.ts:405:12)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /home/john/code/magellan-collections/node_modules/mocha/lib/mocha.js:253:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/john/code/magellan-collections/node_modules/mocha/lib/mocha.js:250:14)
    at Mocha.run (/home/john/code/magellan-collections/node_modules/mocha/lib/mocha.js:577:10)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/mocha/bin/_mocha:591:18)
    at Module._compile (module.js:660:30)
    at Module.replacementCompile (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/john/code/magellan-collections/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at runMain (/home/john/.node-spawn-wrap-14957-e46fc629c0e4/node:68:10)
    at Function.<anonymous> (/home/john/.node-spawn-wrap-14957-e46fc629c0e4/node:171:5)
    at Object.<anonymous> (/home/john/code/magellan-collections/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at /home/john/.node-spawn-wrap-14957-e46fc629c0e4/node:178:8
    at Object.<anonymous> (/home/john/.node-spawn-wrap-14957-e46fc629c0e4/node:181:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

Here is the code that it says those properties aren't defined in.

```ts
export abstract class Exception {
    public message: string;
    public name: string;

    constructor(message: string) {
        const ctor = (this as Object).constructor;

        Error.captureStackTrace(this, ctor);

        this.message = message;
        this.name = ctor.name;
    }
}
```
So they are definitely defined and also the line numbers don't match up either. For the sake of completeness, here is the config for ts-node for mocha and how it is called.

```js
/* config/mocha.config.js */
require('source-map-support/register');
const tsNode = require('ts-node');
tsNode.register({
    compilerOptions: {
        target: 'es5',
        module: 'commonjs',
        sourceMap: true
    } 
});
```

and the npm script that runs it,

`"mocha": "nyc mocha -C --reporter spec config/mocha.config.js \"./src/**/*.spec.ts\""`

**Comment by blakeembrey** [comment]
I'm not sure I follow, 5.0 didn't do any type checking and 6.0 does - is that what you're seeing? There's a lot of extra tools here I'm not familiar with.

**Comment by blakeembrey** [comment]
If you're saying the setup is identical as 5.x and all you did was update, I'd recommend checking the changelog before filing an issue. Major versions mean breaking changes: https://github.com/TypeStrong/ts-node/releases/tag/v6.0.0.

**Comment by JonWallsten** [comment]
I also get an error after updating to 6.0.0.
```
TSError: Ô¿» Unable to compile TypeScript
config\helpers.ts (5,26): Parameter 'path' implicitly has an 'any' type. (7006)
```

This is the code:
```
import { join, resolve } from 'path';

const ROOT = resolve(__dirname, '..');
export const root = (path: string): string => join(ROOT, path);

export const exclude = /(bower_components|public)/;
```

**Comment by frederik-b** [comment]
I' get the following errors with ts-node 6+ but not with 4+ and 5+
(this is using mocha and chai and apparently with and without mocha-typescript)
```
TSError: ⨯ Unable to compile TypeScript
Cannot find global value 'Promise'. (2468)
src/Controller.test.ts (35,42): Property 'includes' does not exist on type 'string[]'. (2339)
src/Controller.test.ts (147,23): Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. (1219)
src/Controller.test.ts (205,16): Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. (1219)
src/Controller.test.ts (224,16): Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. (1219)
src/Controller.test.ts (269,16): Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. (1219)
```
typescript and tslint don't have any of these problems...
is it possible, that the tsconfig is not properly parsed/used?

tsconfig.json:
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "rootDir": "src",
    "outDir": "dist",
    "sourceMap": false,
    "declaration": true,
    "lib": ["es2017"],
    "noImplicitAny": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "newLine": "LF",
    "moduleResolution": "node",
    "typeRoots": ["node_modules/@types", "node_modules/reflect-metadata"],
    "types": ["mocha", "chai", "node"]
  },
  "exclude": ["node_modules", "dist"]
}
```

**Comment by blakeembrey** [comment]
@JonWallsten Are you sure you ran it with `transpileOnly`? It's should be impossible to get type errors in that case. Any type errors are coming from TypeScript, so you'd want to make a reproduction of it first so we can submit the issue with them.

**Comment by blakeembrey** [comment]
@frederik-b Can you create a reproduction of the issue? It's tested in this repo and many others, nor did anything change with parsing from 5.x to 6.x (only the default transpiler mode changed), so I'd like to see what's going on.

**Comment by blakeembrey** [comment]
@JonWallsten That seems unlikely so it'd be awesome if you can double check 😀 This is the only difference between 5.x and 6.x (extremely small, no real changes in code): https://github.com/TypeStrong/ts-node/commit/aa9052d6c56967cf225dda1a8bd55cd79183cefc#diff-f41e9d04a45c83f3b6f6e630f10117feR206. Perhaps there's an issue in that boolean.

**Comment by blakeembrey** [comment]
@JonWallsten Can you double check which versions you're using with `ts-node --version`? How are you using `ts-node`?

**Comment by JonWallsten** [comment]
@blakeembrey I'm running 5.0.1 now. Had just installed 6.0.0 when the issue appeared. Downgraded to 5.0.1 again and the issue disappeared. 

These are the two tries I made:
`"webpack": "ts-node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js",`
`"webpack": "node -r ts-node/register/transpile-only --max_old_space_size=4096 node_modules/webpack/bin/webpack.js",`

**Comment by demisx** [comment]
I've run into the same problem after upgrading to 6.0.1. I have this in `mocha.req.opts` file:

```
--require ts-node/register/transpile-only
--require choma
--colors
...
```

However, still getting typecheck errors similar to:

```
$ nyc mocha --opts test/mocha.req.opts --exit
test/request/helpers.ts (8,33): Could not find a declaration file for module '../../config/db/knexfile-fixtures'. '/Users/dmoore/projects/dimaslist/dimaslist-org-api/config/db/knexfile-fixtures.js' implicitly has an 'any' type. (7016)
test/request/helpers.ts (40,23): Parameter 'opts' implicitly has an 'any' type. (7006)
test/request/helpers.ts (46,23): Parameter 'opts' implicitly has an 'any' type. (7006)
```

Works fine if I explicitly set `typeCheck = false` in `index.js`.

**Comment by blakeembrey** [comment]
@JonWallsten I see, I think webpack is likely requiring `ts-node/register` (with type checking) because it internally registers `ts-node`.

@demisx You might be the same position, IIRC `nyc` also internally registers `ts-node`.

I'm not sure what is ideal, but for now you could control it via environment flags and skip registering it yourself to avoid conflicts.

**Comment by JonWallsten** [comment]
@blakeembrey I guess there's still a big issue here though. Why is the type checker in TS-node showing errors that shouldn't be there? If you check the code in my original message you can clearly see that the variable it complains about actually do have a type. The reason we are discussing turning off the typechecker was just to hide the real problem. Any ideas here?

**Comment by blakeembrey** [comment]
@ondratra What is your `tsconfig.json` file look like?

@JonWallsten If someone provides a reproduction in any shape or form I can take a look, right now I have nothing to work with.

**Comment by blakeembrey** [comment]
For clarification, I tested the code you posted and it worked fine. I need something to show an error so I can figure out what's wrong here.

**Comment by ondratra** [comment]
@blakeembrey ts config is pretty simple:
```
{
target: 'es5',
moduleResolution: 'node',
jsx: 'react',
jsxFactory: 'h',
lib: ["es2017", "dom"]
}
```

**Comment by blakeembrey** [comment]
@ondratra Do you have more complex configuration? Is the `tsconfig.json` file named correctly? In a different directory? I just tested it myself and it worked fine. If you can create a reproduction, it'd greatly help me find the issue.

**Comment by ondratra** [comment]
@blakeembrey I have created minimum repository that shows the error. Just clone and run `yarn run build` and error will happen.

https://github.com/ondratra/ts-node-bug-example

**Comment by blakeembrey** [comment]
@ondratra I tested it and verified, but `tsc` is also broken. You have an invalid `tsconfig.json` file. Sorry, I thought you had a typo in your example above so I corrected it in my example and that's why it didn't fail. You need to put `compilerOptions` under the `compilerOptions` key:

```json
{
    "compilerOptions": {
        "target": "es5",
        "moduleResolution": "node",
        "lib": ["es2017", "dom"]
    }
}
```

**Comment by ondratra** [comment]
@blakeembrey Sorry for providing bugged example project. I fixed issue there and both tsc and ts-node compiles fine even with the newest versions. 
I still got problem in original project (where I don't use tsconfig -> instead I pass parameters right to browserify) and downgrade of ts-node version helps there. 

I will try to explore the issue more and create another example. My wild guess is that there could be change in the way ts-node loads typescript configuration between versions 5.x.x and 6.x.x .

**Comment by blakeembrey** [comment]
@ondratra As I've mentioned, there are no functional changes between 5.x and 6.x, so that isn't possible. The difference is that the default mode reports type errors now. I'm not sure I follow the example of Browserify in relation to `ts-node` though. 

I'm going to close this issue until a reproduction exists, so far all the issues appear to be related to the fact that 6.x is reporting type errors and 5.x did not (by default).

**Comment by blakeembrey** [comment]
@frederik-b @JonWallsten Feel free to share how your projects load `tsconfig.json` and a related file so I can replicate.

**Comment by demisx** [comment]
@blakeembrey Thank you for the tip. In my case, I also had `nyc` configuration in `package.json` that did this:

```js
"nyc": {
    "require": [
      "ts-node/register"
    ],
...
```

Changing it to this did the trick 👍 :

```js
"nyc": {
    "require": [
      "ts-node/register/transpile-only"
    ],
```

**Comment by arindamdat** [comment]
@demisx transpile-only doesn't do type checking. that's why you are not facing the issue
