### ISSUE TITLE
Compiler error  "new () => T"

### ISSUE THREAD

**Issue by aviranco** [TypeStrong/ts-node#713]
Hi,

After upgrading from 6.1.0 to 7.0.1, got compilation errors (in tsc it works, failing only in ts-node),
on usages of `new () => T` like the following:
```
export function doSomething(eventName: string) {
  return <T extends BaseTask>(ctor: new () => T): new () => T => {
    ...
    events[eventName].push(ctor);
    return ctor;
  }
}
```

Which generates the following errors:

```
/Users/aviranc/git/.../node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:

  myfile.ts(16,29): error TS1005: '?' expected.
  myfile.ts(16,35): error TS1005: ')' expected.
  myfile.ts(16,42): error TS1109: Expression expected.
  myfile.ts(16,44): error TS1005: ';' expected.
  myfile.ts(16,48): error TS1005: ';' expected.
  myfile.ts(16,49): error TS1128: Declaration or statement expected.
  myfile.ts(16,56): error TS1109: Expression expected.
  myfile.ts(16,58): error TS1005: ';' expected.
  myfile.ts(16,11): error TS2304: Cannot find name 'T'.
  myfile.ts(16,31): error TS2304: Cannot find name 'ctor'.
  myfile.ts(16,47): error TS2304: Cannot find name 'T'.
  myfile.ts(18,37): error TS2304: Cannot find name 'ctor'.
  myfile.ts(19,12): error TS2304: Cannot find name 'ctor'.
```

Thanks,
Aviran
