### ISSUE TITLE
Error when using ts-node with tsonfig/bases and typescript 5.3.2

### ISSUE THREAD

**Issue by edosrecki** [TypeStrong/ts-node#2088]
After upgrading typescript from 5.2.2 to 5.3.2, I started getting error when using ts-node with tsconfig/bases. See below.

### Expected Behavior
Prints typescript config to standard output.

### Actual Behavior
Error:

```
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '@tsconfig/node20/tsconfig.json' not found.
```

### Steps to reproduce the problem
```sh
npx ts-node --showConfig
```

### Minimal reproduction

https://github.com/TypeStrong/ts-node-repros/pull/36

### Workaround

Use relative path to tsconfig/bases file:
```diff
- "extends": "@tsconfig/node20/tsconfig.json",
+ "extends": "./node_modules/@tsconfig/node20/tsconfig.json",
```

### Specifications

* ts-node version: 10.9.1
* node version: 20.9.0
* TypeScript version: 5.3.2
* tsconfig.json, if you're using one:
```
{
  "extends": "@tsconfig/node20/tsconfig.json",
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "./dist"
  }
}
```
* package.json:
```
{
  "name": "ts-node-bug",
  "version": "0.0.0-dev",
  "devDependencies": {
    "@tsconfig/node20": "20.1.2",
    "ts-node": "10.9.1",
    "typescript": "5.3.2"
  }
}
```
* Operating system and version: MacOS 11.6

**Comment by edosrecki** [comment]
Closing in favor of existing issue: https://github.com/TypeStrong/ts-node/issues/2076

**Comment by bennycode** [comment]
I am also getting `error TS6053: File '@tstv/tsconfig-common/tsconfig.json' not found` when using TypeScript 5.3.2 with ts-node 10.9.1.

Switching from `"extends": "@tstv/tsconfig-common/tsconfig.json"` to `"extends": "./node_modules/@tstv/tsconfig-common/tsconfig.json"` in my `tsconfig.json` quick-fixed it. Thanks for this workaround. 👍

**Comment by edosrecki** [comment]
@bennycode you should upgrade to ts-node 10.9.2 where this was fixed
