### ISSUE TITLE
Cannot find type definition file error on v 6.x

### ISSUE THREAD

**Issue by szeck87** [TypeStrong/ts-node#614]
When upgrading from version 5.0.1 to 6.1.2 we're receiving errors.  I'm not sure why it can't find the definition file.

Repo:  https://github.com/Unibeautify/website/
Script runs:  https://github.com/Unibeautify/website/blob/master/scripts/generate-docs/index.ts

```
return new TSError(diagnosticText, diagnosticCodes)
       ^
TSError: ⨯ Unable to compile TypeScript:
error TS2688: Cannot find type definition file for 'beautifier-prettydiff'.
at createTSError (/opt/build/repo/node_modules/ts-node/src/index.ts:251:12)
at getOutput (/opt/build/repo/node_modules/ts-node/src/index.ts:359:40)
at Object.compile (/opt/build/repo/node_modules/ts-node/src/index.ts:520:13)
at Module.m._compile (/opt/build/repo/node_modules/ts-node/src/index.ts:431:43)
at Module._extensions..js (module.js:660:10)
at Object.require.extensions.(anonymous function) [as .ts] (/opt/build/repo/node_modules/ts-node/src/index.ts:434:12)
at Module.load (module.js:561:32)
at tryModuleLoad (module.js:501:12)
at Function.Module._load (module.js:493:3)
at Function.Module.runMain (module.js:690:10)
```

**Comment by blakeembrey** [comment]
Your `tsconfig.json` file is wrong: https://github.com/Unibeautify/website/blob/f77c8578857f6da3628c19409feda2b313751af7/tsconfig.json#L21.
