### ISSUE TITLE
"error TS2304: Cannot find name" after updating to 7.0.0

### ISSUE THREAD

**Issue by ellipticaldoor** [TypeStrong/ts-node#615]
I updated ts-node from 6.2.0 to 7.0.0 and I started to get the following error:
``` js
TSError: ⨯ Unable to compile TypeScript:
src/common/atlas/atlas.constants.ts(3,27): error TS2304: Cannot find name 'Tile'.
src/common/atlas/atlas.constants.ts(6,31): error TS2304: Cannot find name 'ITileLayer'.
src/common/atlas/atlas.constants.ts(27,28): error TS2304: Cannot find name 'ITileLayer'.

    at createTSError (/Users/miguel/src/later/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Users/miguel/src/later/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Users/miguel/src/later/node_modules/ts-node/src/index.ts:557:11)
    at Module.m._compile (/Users/miguel/src/later/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at require.extensions.(anonymous function) (/Users/miguel/src/later/node_modules/ts-node/src/index.ts:442:12)
    at Object.nodeDevHook [as .ts] (/Users/miguel/src/later/node_modules/node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
[ERROR] 11:14:48 TSError
```

It looks like this version is not able to find my custom type definitions. I recently started to learn typescript so I'm not sure if what I'm doing is good practice, this is my folder structure

![image](https://user-images.githubusercontent.com/3449006/41808550-0e2c845e-76d7-11e8-997f-498f6c7bb5e8.png)

Y put my types inside *.d.ts files and nothing more, this worked before updating.

Not sure if this can help but here is my .tsconfig

``` json
{
	"compilerOptions": {
		"strict": true,
		"alwaysStrict": true,
		"module": "commonjs",
		"moduleResolution": "node",
		"types": ["node", "jest", "pixi.js", "matter-js"],
		"newLine": "LF",
		"outDir": "lib",
		"jsx": "preserve",
		"target": "es2017",
		"lib": [
			"es2017",
			"dom"
		],
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noImplicitAny": true,
		"noFallthroughCasesInSwitch": true,
		"experimentalDecorators": true,
		"baseUrl": "./src",
		"paths": {
			"common/*": [
				"./common/*"
			],
			"client/*": [
				"./client/*"
			],
			"server/*": [
				"./server/*"
			]
		}
	},
	"include": [
		"src/common/**/*.ts",
		"src/client/**/*.ts"
	],
	"exclude": [
		".git",
		"node_modules"
	]
}

```

**Comment by polco** [comment]
I have the same issue, my custom types files are not loaded anymore with the version 7.

**Comment by blakeembrey** [comment]
A major version means breaking changes. If something breaks, you can check the changelog or commits to see what happened. See https://github.com/TypeStrong/ts-node/releases/tag/v7.0.0 and the notice in the README. If they aren't clear, feel free to clarify them. If you'd like the old behaviour for now, you can use `ts-node --files`.

**Comment by blakeembrey** [comment]
@weswigham Would you be kind enough to share the recommended way someone should include these files into their `ts-node` project (without `--files`)?

**Comment by ellipticaldoor** [comment]
Yes, I would like to know how is the proper way.

**Comment by jeremejevs** [comment]
Why make a major release so quickly? I do agree that, as @weswigham says, "the build orchestrator is not part of the build it orchestrates", but the fix is kind of on the extreme side. Why not at least try taking some useful parts out of the `tsconfig.json`, if there is one? `esModuleInterop`, `lib`, `typeRoots`, `exclude`, the strictness settings, etc.

Sticking to v6 for now, since I don't want to:

- Maintain a separate `tsconfig.json` just for `ts-node`.
- Augment every single `ts-node` invocation with a `--project`.
- Use triple-slash pragmas where I previously didn't have to.

It's possible that I'm in the tiny minority here, but the discussion was way too short for this change, IMO.

**Comment by blakeembrey** [comment]
@jeremejevs You assume I haven't thought about this for the past three years of working on this module, which I actually have. There's been many iterations on the "correct" approach, but I agreed this one was the most appropriate today given `types` and other TypeScript features introduced since 2.0. 

> Why not at least try taking some useful parts out of the tsconfig.json, if there is one? esModuleInterop, lib, typeRoots, exclude, the strictness settings, etc.

You can't just magically introduce a flag that controls which files get type checked. I'm not sure how you believe those flags would play into this? Are you expecting `ts-node` to mess with your settings (which, FWIW, is exactly what this is doing and you're objecting to). 

You don't even need to maintain a separate `tsconfig.json` for `ts-node` - this changed works for all my projects using `ts-node` without separate configuration. What's not working for you?

**Comment by blakeembrey** [comment]
FWIW, I'm going to have to assume you're having issues with trying to "global" types into your project. Those aren't particularly recommended today as it makes your code fragile to conflicting types and unable to interop with dependents. You can instead put your types in modules, export and import them where needed instead of having them "everywhere". 

Another thing, you can use `ts-node --files` to include "all" files if that's what you really want. You just have to be aware project startup can be slow. The new default alleviates some issues such as, in the past, you could have `ts-node` stall forever by spawning the REPL in the home directory (causing TypeScript to, by default, crawl everything in the directory looking for types).

**Comment by jeremejevs** [comment]
@blakeembrey Poor reading skills this time of day + didn't look at the diff. Interpreted "Skip loading `tsconfig.json` files by default to speed up startup" as "`tsconfig.json` is ignored now". Sorry.

What do you mean by "global" types? I have a few of these:

```ts
// typings/some-npm-package.d.ts
declare module "some-npm-package" {
  // ...
}
```

And `typeRoots: [./typings]` in the config. v6 sees them, v7 doesn't.

**Comment by blakeembrey** [comment]
Feel free to submit corrections to how it's phrased. I know I can be terrible at that and don't typically spend enough time thinking about all the ways it's interpreted. 

As for `typeRoots`, it should still be working - let me create double check for you, give me 15 minutes or so.

**Comment by blakeembrey** [comment]
@jeremejevs Found the issue - looks like your `typeRoots` wasn't doing anything because it needs to be a directory and `index.d.ts` (e.g. `typings/some-npm-package/index.d.ts`). Looks like it worked because you have `include` or something else globbing it to be included. This has been a fun exercise, spotted a bug with the `cache` flag after much head banging, and learned more about `types` and `typeRoots`.

**Comment by salemdar** [comment]
How can we pass files flag when we are using TypeScript for gulp tasks?

**Comment by jeremejevs** [comment]
@blakeembrey Thank you for taking time to look into this. Decided to investigate this myself, and wow, still got some misconceptions. Everything was working, so I was sure I had it all figured out...

Indeed, `typeRoots` was doing nothing. The typings were being picked up by TypeScript's default `include` (my `tsconfig.json` has only an `exclude`). **And** it wouldn't work even if the typings did have the right shape, since `typeRoots` is for global declarations. Need to use `paths` for that, which is conveniently omitted in [`tsconfig.json` docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html), and is instead described in [module resolutions docs](https://www.typescriptlang.org/docs/handbook/module-resolution.html).

The fix is to put this in place of `typeRoots`:

```json
"baseUrl": ".",
"paths": { "*" : ["typings/*"] }
```

And translate all typings from `typings/*.d.ts` to `typings/*/index.d.ts`, i.e. from this:

```ts
// typings/some-npm-package.d.ts
declare module "some-npm-package" {
  const x: string;
  export = x;
}
```

To this:

```ts
// typings/some-npm-package/index.d.ts
declare const x: string;
export = x;
```

I'm choosing this approach because I always wanted my typings to look the same as what you would find on DefinitelyTyped, and now it's possible, **and** it works with both `ts-node` and `tsc`.

I also have typings like this:

```ts
// typings/svg.d.ts
declare module "*.svg" {
  const x: string;
  export default x;
}
```

These are okay to leave as-is, since they make sense only in the context of a bundler like Webpack, and `ts-node` shouldn't be able to execute files which import SVGs and such. One exception is JSON, but [there's a setting for it now in TS 2.9](https://stackoverflow.com/a/50674344/242684). This way, there's no need in involving `typeRoots` at all.

I'm glad this change broke my stuff, now I have a better config and a better understanding of it, thanks.

**Comment by blakeembrey** [comment]
I’m not as glad it broke things for people (it’s one of many “the lesser of two evils” but trying to figure out which evil is which is the hard part), but I’m thankful for your investigation work!

**Comment by g-harel** [comment]
I really feel like there should be more context in the release notes for a major version.

**Comment by dsifford** [comment]
For the lazy webpack users that are running into this issue:

Assuming the following....
1. You don't feel like refactoring.
2. You are starting webpack using an npm script like this...

```json
{
  "scripts": {
    "start": "webpack"
  }
}
```

Simply change it to this and it'll work like before:

```json
{
  "scripts": {
    "start": "TS_NODE_FILES=true webpack"
  }
}
```

**Comment by freezy** [comment]
@lddubeau: You can also set an environment variable instead of `--files`, which will the picked up through Gulp.

@blakeembrey: Whichever evil you choose, describing it more explicitly in the release notes would have saved us all a lot of time!

**Comment by blakeembrey** [comment]
Feel free to submit an issue with a better description that you’d like to see.

**Comment by freezy** [comment]
From my admittedly limited understanding, maybe:

> If your project contains merge declarations that aren't in the dependency tree, it's possible to fall back to the previous behavior by setting the `--files` flag or the `TS_NODE_FILES` environment variable.

But then, putting the declarations in the correct folder like @jeremejevs suggests seems to work too.

**Comment by ljani** [comment]
@jeremejevs You are not using [`tsconfig-paths`](https://github.com/dividab/tsconfig-paths/) with that configuration, are you? Because It looks like `tsconfig-paths` seems to think that `typings/some-npm-package` should also contain `index.js` file:

```
Error: Cannot find module 'C:\...\my-project\types\postcss-nested'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._resolveFilename (C:\...\my-project\node_modules\tsconfig-paths\lib\register.js:29:44)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
...
```

I'm facing this problem when a webpackfile needs ambient typings for `postcss-nested`:

```
webpack-dev-server --config-register tsconfig-paths/register
```

**Comment by jeremejevs** [comment]
@ljani Sorry, I'm not. It appears that my "fix" clashes with the assumptions that `tsconfig-paths` is making about the usage of `paths`. The only workaround that comes to my mind is to have a separate `tsconfig.json` for now, which doesn't have these `baseUrl`/`path` changes. But I think this should be solved on their side, maybe by adding a flag, which lets you tell it to ignore certain `paths` keys or something like that.

**Comment by ljani** [comment]
@jeremejevs Thanks for confirmation! I wanted to make sure it was not a misconfiguration on my part.

**Comment by blakeembrey** [comment]
@ljani How did you use these definitions before? If they're still global (e.g. `declare module "x"`), you can use `typeRoots`. If they're modules, I'm not sure how you could have made TypeScript discover them before because the module file doesn't directly map to a module name without `paths` configured.

**Comment by ljani** [comment]
They're global. I didn't even try `typeRoots`, because of a previous bad experience from misunderstanding them. @jeremejevs was so convincing, that I decided to try his solution first. If I specify `typeRoots: : ["./typings", "./node_modules/@types"]`, will it include types from eg. `./node_modules/@material-ui/core/index.d.ts`, if I import a module from `material-ui`?

**Comment by blakeembrey** [comment]
@ljani That should work 👍

**Comment by ljani** [comment]
@blakeembrey Great! Thanks for letting me know. First time I tried TypeScript, I think I forgot to include `./node_modules/@types` in `typeRoots` and thus it seemed to break everything. It has been a while :-)

**Comment by ljani** [comment]
@blakeembrey It works, thanks again. Do you happen to know why at least TS language service gets confused if `typeRoots` contains wildcard modules? I'm trying to share eg. this one between two modules:

```
declare module "*.png";
```

It works fine if I add the file directly to the modules.

**Comment by 19majkel94** [comment]
What about ambient module declaration for module augmentation?
```ts
declare namespace NodeJS {
  interface Global {
    TypeGraphQLMetadataStorage: import("../metadata/metadata-storage").MetadataStorage;
  }
}
```
I've tried `typeRoots` and `paths` tricks but no success 😞

**Comment by blakeembrey** [comment]
@19majkel94 Can you share your configuration so we can see why it didn't work? 

@ljani Thanks for your investigations! It'd be worth adding a section to the README on how to set this up correctly, I'll try that tonight 😄

**Comment by 19majkel94** [comment]
@blakeembrey It doesn't work because `typeRoots` and `paths` are used only for module resolution for looking when using `import`, not when the module is found but additional declarations are in other file in the project.

Here's quick reproduction gist:
https://gist.github.com/19majkel94/4799a197d238639752a29333a78cc7d9

**Comment by blakeembrey** [comment]
@19majkel94 That's not true, `typeRoots` is for global definitions.

**Comment by 19majkel94** [comment]
@blakeembrey So any idea why the gist is not working? 🤔

**Comment by blakeembrey** [comment]
@19majkel94 There's documentation and links in this thread pointing out what you've run into. You need to make it a directory and use `index.d.ts`.

**Comment by blakeembrey** [comment]
I'll be working this week on improving documentation/introduction on how to use these features in TypeScript - it's definitely not clear from the TypeScript side given the number of comments/issues.

**Comment by 19majkel94** [comment]
Thanks, it's awful but it works - I wonder how `deno` solves that problem 🤔

**Comment by samjmckenzie** [comment]
@ljani Could I possibly see your `tsconfig.json` configuration? I can't get mine to resolve types that aren't in `node_modules/@types`.

**Comment by ljani** [comment]
@samjmckenzie Sure, this one is from a monorepo where the `package.json` is above all of the packages. The file is located in `src` and there's a `types` directory next to the `src` folder:

```
{
  "extends": "../../../tools/tsconfig-web.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*": [
        "*",
        "../types/*"
      ]
    },
    "typeRoots": [
      "../../../node_modules/@types",
      "../types"
    ]
  }
}
```

The `types` folder contains other folders with the module names and those contain `index.d.ts` files.

In `tsconfig-web.json`, `"moduleResolution": "node"` is the only thing, which affects *path* resolution. But in addition I'm using and `"lib": ["esnext", "dom"]`, `allowSyntheticDefaultImports` and `esModuleInterop` there.

Hope this helps.

**Comment by samjmckenzie** [comment]
Thanks, but unfortunately I can't get it working. Oh well. I will just have to keep using the `--files` option.

**Comment by ljani** [comment]
Actually the way `paths` is used in my example has at least one drawback. For example `webpack` seems to be making `require("crypto")` calls and this yields thousands of disk lookups for `crypto`, `crypto.js`, `crypto.ts` etc in the two paths. I'm not sure what's the performance impact, but I thought you guys should know.

Also now that I come to think about this, is [this test](https://github.com/TypeStrong/ts-node/blob/ad6183a1b99df4f535903e7b51ce99571221c95b/src/index.spec.ts#L257) wrong? Shouldn't it be `expect(err).not.to.match(/Error: Cannot find module 'does-not-exist'/)`, because [the typings](https://github.com/TypeStrong/ts-node/blob/ad6183a1b99df4f535903e7b51ce99571221c95b/tests/typings/does-not-exist/index.d.ts) do exist?

**Comment by blakeembrey** [comment]
@ljani The test is correct. That’s a runtime error, not a compilation error. As for lookups, just don’t use the wildcard too heavily - there’s a difference between `paths` and `types` too.

**Comment by ljani** [comment]
Ah, right. However, if I remove the whole `typings` folder (at least on Windows), the test still passes. Any idea why?
