### ISSUE TITLE
Error: unknown file extension .ts

### ISSUE THREAD

**Issue by Thomas1664** [TypeStrong/ts-node#1062]
### Expected Behavior
Load typescript files

### Actual Behavior
When I try to execute a typescript file I get the following error message:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/$USERNAME/$PATH_TO_DEV_FOLEDER/index.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:113:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at Loader.import (internal/modules/esm/loader.js:177:17)

### Steps to reproduce the problem
launch ts-node index.ts

### Specifications

* ts-node version: v8.10.2 (installed global)
* node version: v14.3.0
* TypeScript version:v3.9.3 (installed global)
* tsconfig.json, if you're using one:
```
{}
```
* Operating system and version: Windows 10 Version 2004
* If Windows, are you using WSL or WSL2?: Yes, Ubuntu 20.04 LTS in WSL2

**Comment by cspotcode** [comment]
ESM stuff?  You might have better luck on our ESM thread.  Or post a complete reproduction so someone else can debug.

**Comment by alexcochran** [comment]
I'm having the same issue.

```
λ npx ts-node src/app.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\Users\$USER\$PATH_TO_DEV_FOLDER\src\app.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:113:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at Loader.import (internal/modules/esm/loader.js:177:17)
```

**Comment by Aguinaldo-Alberto-Naldo** [comment]
Estou tendo também o mesmo problema

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for rc\server.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:113:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at Loader.import (internal/modules/esm/loader.js:177:17)

**Comment by Aguinaldo-Alberto-Naldo** [comment]
Estou tendo o mesmo problema também

`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for www\server\src\server.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:113:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at Loader.import (internal/modules/esm/loader.js:177:17)`

**Comment by cspotcode** [comment]
My earlier suggestion should point you in the right direction.

**Comment by clinkadink** [comment]
Remove "type": "module" from package.json

**Comment by SaintPhill** [comment]
> Remove "type": "module" from package.json

If remove module type, you cannot use imports in your .ts files

**Comment by Thomas1664** [comment]
I must disagree. In Angular projects, there is no "type": "module" in package.json and import synthax works fine. Try to set "module": "es2020" in tsconfig.json

**Comment by SaintPhill** [comment]
> I must disagree. In Angular projects, there is no "type": "module" in package.json and import synthax works fine. Try to set "module": "es2020" in tsconfig.json

nope, same problem with import. 
"Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension."

**Comment by Thomas1664** [comment]
I created a [template repo](https://github.com/Thomas1664/ts-node-template) which can be sued by anyone who has trouble initializing ```ts-node```.

**Comment by cspotcode** [comment]
Closing as this is not a `ts-node` bug.  If you want to use node's native ESM support, which is currently experimental, then you can use `ts-node`'s experimental ESM loader hook.  See #1007 for details.

**Comment by dandv** [comment]
Calling `ts-node myscript` without the file extension, works for me.

**Comment by paxperscientiam** [comment]
@clinkadink thanks, that did it for me

**Comment by cspotcode** [comment]
We've enabled the discussion forum for questions like this one.

https://github.com/TypeStrong/ts-node/discussions

We're trying to keep the issue tracker limited to *actionable* tasks, so contributors can focus on making fixes and improvements to `ts-node`.

Since this is not a bug and nothing needs to change in `ts-node`, it's not actionable, so it was closed.  Discussions, on the other hand, are the perfect place to ask advice, share guides, and help with project configuration.

Another good thing about the discussion forum: you don't need to fill out an issue template.

**Comment by a-h** [comment]
This stack overflow answer helped me: https://stackoverflow.com/questions/63445821/ts-node-execute-typescript-with-module-import-and-module-defined

Updating my tsconfig.json to migrate from `"module": "es6"` to `"module": "commonjs"` allowed me to run my TypeScript file.

**Comment by kseebrinegar** [comment]
@a-h Thank you bro! you the man!

**Comment by buzuosheng** [comment]
> > Remove "type": "module" from package.json
> 
> If remove module type, you cannot use imports in your .ts files

I'm having the same issue. how to fix, thx

**Comment by itcat99** [comment]
> This stack overflow answer helped me: https://stackoverflow.com/questions/63445821/ts-node-execute-typescript-with-module-import-and-module-defined
> 
> Updating my tsconfig.json to migrate from `"module": "es6"` to `"module": "commonjs"` allowed me to run my TypeScript file.

Thanks! it's useful.

**Comment by Rollingegg** [comment]
From [#1007](https://github.com/TypeStrong/ts-node/issues/1007), use `node --loader ts-node/esm ./my-script.ts` if your `tsconfig.json` contains `"module": "commonjs"`

**Comment by shanoysinc** [comment]
I remove type: module from package json and it work

**Comment by Abeautifulsnow** [comment]
> This stack overflow answer helped me: https://stackoverflow.com/questions/63445821/ts-node-execute-typescript-with-module-import-and-module-defined
> 
> Updating my tsconfig.json to migrate from `"module": "es6"` to `"module": "commonjs"` allowed me to run my TypeScript file.

This solution resolves my two problems which are "import" syntax-error outside module and unknown file extensions ".ts"!!! Thank you very much for saving my time. 😁

**Comment by iway1** [comment]
Add this to the tsconfig.json:

```
  "compilerOptions": {
    "esModuleInterop": true
  }
```

and make sure to start the server with `ts-node`:

```
ts-node my_ts_node_server.ts
```

It is *crazy* how hard it was for me to find this. This will allow you to use imports as well as use typescript.

**Comment by Mehak-Mehta** [comment]
> Add this to the tsconfig.json:
> 
> ```
>   "compilerOptions": {
>     "esModuleInterop": true
>   }
> ```
> 
> and make sure to start the server with `ts-node`:
> 
> ```
> ts-node my_ts_node_server.ts
> ```
> 
> It is _crazy_ how hard it was for me to find this. This will allow you to use imports as well as use typescript.

Yup that works!!

**Comment by JakeCover** [comment]
> From [#1007](https://github.com/TypeStrong/ts-node/issues/1007), use `node --loader ts-node/esm ./my-script.ts` if your `tsconfig.json` contains `"module": "commonjs"`

Real quick follow up to this - running with this makes my code ~8x slower than `ts-node` by itself with changed options or just using `tsc` and `node`, and that's testing the same exact function 10 times in a loop to mitigate the effects of the typescript JIT compilation times. Hopefully this is useful to someone?

**Comment by mickymac19** [comment]
This is what worked for me 
ts-node: 10.2.1
typescript: 4.4.2
node: 16.8.0 

in package.json 
I removed 
"target": "module" 

in tsconfig.json I added this 

"ts-node": {
    "compilerOptions": {
     "module": "commonjs"
    }
   
   an in a separate 
   "compilerOptions" 
   "module": "ESNEXT" 
   
   I was getting a different error which is "Cannot use import statement outside a module" 
   as a suggested solution in stack overflow 
   I added "target":"module" in package.json 
   which lead me to this error: unknown file extension .ts 
   
   Hope it helps you out. I also found this article
 https://www.tsmean.com/articles/learn-typescript/typescript-module-compiler-option/

**Comment by jwalton** [comment]
I spent an hour banging my head against a wall this morning trying to figure this out - if you have a dependency in your project which uses `"type": "module"` in it, it can also cause this problem.  In my case, I had `node-fetch@3.1.0`.  Downgrading to `node-fetch@2.5.12` fixed it for me.

**Comment by gstamac** [comment]
> "type": "module"

After hours lost this is the "solution". Thanks.

**Comment by Stevemoretz** [comment]
> I spent an hour banging my head against a wall this morning trying to figure this out - if you have a dependency in your project which uses `"type": "module"` in it, it can also cause this problem. In my case, I had `node-fetch@3.1.0`. Downgrading to `node-fetch@2.5.12` fixed it for me.

What if you can not do that :)?
That's not a solution.

**Comment by cspotcode** [comment]
The --loader is sometimes necessary.  There are myriad issues where this is discussed, plus node's documentation.  When searching, be sure to check the discussion forum and include closed issues in your search.  Pull requests which improve documentation are always welcome if you feel that is appropriate.

**Comment by greenlucid** [comment]
@Stevemoretz Unfortunately I think the issue is in node-fetch's end. I tried every configuration after losing an hour to this mindlessness and I'm not planning on wasting more time on it

**Comment by Stevemoretz** [comment]
> @Stevemoretz Unfortunately I think the issue is in node-fetch's end. I tried every configuration after losing an hour to this mindlessness and I'm not planning on wasting more time on it

Me too unfortunately I revered back to js for now.

**Comment by jwalton** [comment]
If you think node-fetch is the issue, you need to downgrade to a pre-3.0.0 version.  In 3.0.0, they changed the module to be ESM-only.  It no longer exports a CJS version.  "chalk" is another package that did this, starting with 5.0.0.

When we get down into the weeds, the real problem here is that node won't let you synchronously "require" an ESM module.  This is kind of obnoxious - it obviously wouldn't be a terribly difficult thing to add to node, since Babel and TypeScript both manage to interop between CJS and ESM, but this is the world we live in.  :/

**Comment by eliellis** [comment]
I'd like to report some success just for any lost soul who's found there way here. I've found the below works fine for me–and mind you, this is "all modern" Typescript output as well as the Node `"type": "module"` use case, so YMMV but it certainly works with all of @sindresorhus's newest ESM-only packages (`find-up`, `chalk` etc.). Seems to also work for standard-issue CommonJS packages.

_tsconfig.json_
```json
{
  "compilerOptions": {
    "target": "esnext",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "module": "esnext",
    "rootDir": "./src",
    "moduleResolution": "node",
    "types": ["node"],
    "resolveJsonModule": true,
    "outDir": "./dist/",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "include": ["./src/**/*.ts"]
}
```

_package.json_
```json
{
    // ...
    "type": "module"
   // ...
}
```

and the `ts-node` command: `node --experimental-specifier-resolution=node --loader ts-node/esm src/main.ts`

**Comment by LetrixZ** [comment]
https://github.com/TypeStrong/ts-node/issues/1062#issuecomment-1028139483
It works perfectly but how could I use with nodemon (or similar) to watch for changes? 
Tried with nodemon --exec but wasn't detecting any change.

**Comment by Rush** [comment]
I am trying to use Typescript from Webpack but latest Angular updater their webpack plugins to ESM. :D Eh, the ESM is such a disaster that one can only laugh. So many hours needlessly wasted.

**Comment by LeDucLoi193** [comment]
This is the solution for me, hope it helps someone
I'm using Express 4.17.3, Node 14.17.0
- Install ts-node 10.7.0 as devDependencies
- In package.json file, remove "type": "module"
- In tsconfig.json file, use "module": "commonjs"

### My package.json file: 
```
{
  "name": "xxx",
  "version": "1.0.0",
  "main": "index.js",
  "author": "xxx",
  "license": "MIT",
  "scripts": {
    "ts-check": "tsc --noemit",
  },
  "dependencies": {
    "express": "^4.17.3",
    "tslib": "^2.3.1"
  },
  "devDependencies": {
    "@types/express": "^4.17.13",
    "@types/node": "^17.0.23",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.3"
  }
}
```

### My tsconfig.json file: 

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "baseUrl": ".",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "inlineSources": true,
    "isolatedModules": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "paths": {
      "@routes/*": ["src/routes/*"],
      "@config/*": ["src/config/*"],
      "@controllers/*": ["src/controllers/*"],
      "@models/*": ["src/models/*"],
      "@utils/*": ["src/utils/*"],
      "@socket/*": ["socket/*"],
      "@src/*": ["src/*"],
    },
    "preserveConstEnums": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "es5",
    "removeComments": true,
    "importHelpers": true,
    "typeRoots": ["./node_modules/@types"],
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "dist"]
}
```

**Comment by nccurry** [comment]
Following this ts-node documentation [CommonJS vs native ECMAScript modules](https://typestrong.org/ts-node/docs/imports/) worked for me.

I removed ```"type": "module",``` from ```package.json``` and added ```"module": "commonjs",``` to ```tsconfig.json``` and it resolved the issue.

**Comment by ExProbitasFiducia** [comment]
> I must disagree. In Angular projects, there is no "type": "module" in package.json and import synthax works fine. Try to set "module": "es2020" in tsconfig.json

literally what does angular have to do with node??? doesn't matter if you're using babel. the question is about using typescript with node so thank you for reading and understanding the question carefully in order to provide constructive and helpful guidance. Great job author!

**Comment by kshetline** [comment]
No matter what I do, I can't get beyond "Unknown file extension ".ts"". My project is in TypeScript, and I'm trying to import an npm package (double-metaphone) that only working as an ESM import. Since I'm trying run my code using:

`node --experimental-specifier-resolution=node --loader ts-node/esm app.ts`

...it seems utterly bizarre that I would get an error complaining about the ".ts" extension. What other than ".ts" would the ts-node loader expect?

I've tried various combinations and permutations of suggestion here and elsewhere. My latest setup, running under Node.js v16.13.1, looks like this:

```
{
  "name": "my-project",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "start": "node --experimental-specifier-resolution=node --loader ts-node/esm app.ts",
  },
  "dependencies": {
    // blah, blah, blah
    "double-metaphone": "^2.0.0",
    // blah, blah, blah
  },
  "devDependencies": {
    // blah, blah, blah
    "ts-node": "^10.0.0",
    "typescript": "^4.5.4"
  }
}
```

```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "sourceMap": true,
    "outDir": "./tsc-out",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2020",
      "dom"
    ]
  },
  "ts-node": {
    "esm": true
  }
}
```

**Comment by Divide-By-0** [comment]
I added "type": "module" in package.json and did `npx tsx file.ts` instead of using `ts-node file.ts` and it worked.

**Comment by cspotcode** [comment]
You probably needed to enable `"esm": true`

**Comment by aravindvakil** [comment]
if your tsconfig.json contains "module": "ESNext". I have used the below script in my package.json. It worked.

```
 "start": "nodemon -e ts -w ./src -x npm run watch:serve",
 "watch:serve": "node --loader ts-node/esm src/server.ts",
```

**Comment by joemullenix-ks** [comment]
To all the poor souls still battling this like me: I might have a solution with ESM, "type: "module" _and_ ts-node for VSCode. It involves adding a --loader runtime arg to launch.json. I hope it helps!

(Windows, Node 18.2.0)

**package.json:**
{
   ...
  "main": "source/main.js",
  "type": "module",
  "devDependencies": {
    "@types/node": "^18.6.1",
    "ts-node": "^10.9.1"
  }
}

**tsconfig.json:**
{
	"$schema": "https://json.schemastore.org/tsconfig",
	"display": "Node 16",
	"compilerOptions":
	{
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"lib": ["es2020"],
		"module": "ESNext",
		"outDir": "output",
		"skipLibCheck": true,
		"strict": true,
		"target": "es2020"
	},
	"include": ["source"],
	"exclude": ["node_modules"],
	"ts-node":
	{
		"esm": true // from the top of https://typestrong.org/ts-node/docs/imports/
	}
}

**launch.json:**
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
		{
			"name": "TS Debug",
			"type": "node",
			"request": "launch",
			"cwd": "${workspaceRoot}",
			"runtimeArgs": ["-r", "ts-node/register", "--loader", "ts-node/esm"],
			"args": ["${workspaceRoot}/source/runme.ts"]
		  }
    ]
}

With this, I can use ESM import/export, run the VSCode debugger, catch breakpoints in my TS files, etc...

**Comment by dfenerski** [comment]
What the actual <> is this and why is it closed when it breaks on node 16? No reliable solutions in the comments so far.

**Comment by norasotanext** [comment]
> node-fetch@2.5.12

it is actually the solution :D

**Comment by norasotanext** [comment]
> > I spent an hour banging my head against a wall this morning trying to figure this out - if you have a dependency in your project which uses "type": "module" in it, it can also cause this problem. In my case, I had node-fetch@3.1.0. Downgrading to node-fetch@2.5.12 fixed it for me.
> 
> After hours lost this is the "solution". Thanks.

It is actually the solution :D

**Comment by jxeng** [comment]
Use `ts-node --esm`,  `ts-node-esm`, or set `"esm": true` in tsconfig.json

https://typestrong.org/ts-node/docs/imports/

**Comment by augustoaraujoo** [comment]
remove type: "module" and add in your tsconfig.json "compilerOptions":{  "module": "Commonjs",
    "moduleResolution": "node" }

**Comment by blascokoa** [comment]
> Remove "type": "module" from package.json

This worked for me, despite theoretically imports cannot be used, here is my seed code:

```ts
import { PrismaClient } from '@prisma/client'
import { links } from '../data/links'

const prisma = new PrismaClient()

async function main() {
  await prisma.user.create({
    data: {
      email: "testemail@gmail.com",
      role: "ADMIN",
    },
  })
  await prisma.link.createMany({
    data: links,
  });
}


main().catch((e) => {
  console.log(e);
  process.exit(1);
}).finally(async () => {
  await prisma.$disconnect();
});
```

And here you can find my package.json:

```json
  "version": "0.1.0",
  "prisma": {
    "seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts"
  },
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "ts-node": "ts-node --compiler-options '{\"module\":\"commonjs\"}'"
  },

```

**Comment by karliell** [comment]
For me, I use `nodemon` to solve this issue. 

tsconfig.json
```
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "lib": ["esnext"],
    "esModuleInterop": true,
  },
}
```

package.json
```
{
  "name": "prisma_learn",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "devStart": "nodemon script.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^18.11.9",
    "@typescript-eslint/eslint-plugin": "^5.42.0",
    "eslint": "^8.27.0",
    "eslint-config-standard-with-typescript": "^23.0.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-n": "^15.5.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.31.10",
    "nodemon": "^2.0.20",
    "prisma": "^4.5.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4"
  },
  "dependencies": {
    "@prisma/client": "^4.5.0"
  }
}
```
script.ts
```
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  const user = await prisma.user.create({ data: { name: 'Kyle' } });
  console.log(user);
}

main()
  .catch((e) => {
    console.error(e.message);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```

**Comment by AndresPrez** [comment]
For me adding the `--esm` for `ts-node --esm index.ts` command did it.

**Comment by mikemaccana** [comment]
For me adding `--esm` did not work. I received the error:

```
CustomError: Cannot find module '/home/mike/Code/company/app/src/backend/functions' imported from /home/mike/Code/company/app/do-thing.ts
``` 

The file `/home/mike/Code/company/app/src/backend/functions.ts` does exist (and I shouldn't need the .ts to load it in TS). 

However using `npm tsx` as others have mentioned did fix the problem and allowed my code to run perfectly.

**Comment by berekmerilorand** [comment]
Receiving unknown file extension ".ts" error after upgrading wdio to 8 and Appium >16.

Detailed description [here](https://github.com/TypeStrong/ts-node/issues/1584#issuecomment-1380397569).

**Comment by linbaijin** [comment]
tsconfig.json
` "compilerOptions": {
        "module": "nodenext",
        "moduleResolution": "nodenext"
}
`

**Comment by GrayJyy** [comment]
> tsc && node --experimental-specifier-resolution=node dist/main.js

tks!!!!!!it works for me.

**Comment by retrotechie** [comment]
**Solution 1**:

Remove `"type": "module"` in package.json

**Solution 2**:

package.json
```json
...
"type": "module"
...
```

tsconfig.json
```json
"compilerOptions": {
...
"module": "ESNext",
...
},
"ts-node": {
  "esm": true
}
```

I'm not sure if we had better solutions but these worked for me.

**Comment by rtritto** [comment]
This https://github.com/nodejs/node/pull/43772 should help/fix (currently it's released in Node v19.6.0 and there is a backport to v18).

**Comment by xgqfrms** [comment]
# ESM solution ✅

![image](https://user-images.githubusercontent.com/7291672/226874952-ebc93ed7-b9d4-4215-b9a5-006965262fde.png)


> `"type": "module",` &  `ts-node-esm` 

```json
{
  "name": "patch-package-in-action",
  "version": "1.0.0",
  "description": "patch-package in action",
  "main": "./src/index.ts",
  "type": "module",
  "scripts": {
    "dev-esm": "npx ts-node-esm ./src/index.ts",
    "app-esm": "npx ts-node-esm ./src/app.ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/web-fullstack/patch-package-in-action.git"
  },
  "author": "xgqfrms",
  "license": "MIT",
  "dependencies": {
    "lodash-es": "^4.17.21",
    "typescript": "^5.0.2"
  },
  "devDependencies": {
    "@types/lodash-es": "^4.17.7",
    "app-node-env": "^1.4.7",
    "rimraf": "^4.4.0",
    "ts-node": "^10.9.1"
  }
}


```

> `esm`

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "ts-node": {
    "esm": true
  },
}

```

```ts

import {toString} from "lodash-es";

type Obj = {
  [key: string]: any;
}

const obj: Obj = {
  name: 'xgqfrms',
  country: 'China',
  language: 'zh-hans',
};

const str = toString(obj);
console.log(`toString =`, str1);

```

## refs

https://typestrong.org/ts-node/docs/imports/

**Comment by leonasdev** [comment]
I just `rm -rf dist` and `tsc` & `node dist/index.js` again, then it works.

**Comment by VladBrok** [comment]
> What worked for me is `ts-node --esm <filename>`. No `esModuleInterop` or `package.json` changes

@dfenerski thanks

**Comment by neerajkumar161** [comment]
```ts
"ts-node": {
  "esm": true
}
```
This worked for me. Thanks, @retrotechie :rocket:

**Comment by JuYiYang** [comment]
> Remove "type": "module" from package.json
remain invalid

**Comment by 88brmig** [comment]
> if your tsconfig.json contains "module": "ESNext". I have used the below script in my package.json. It worked.
> 
> ```
>  "start": "nodemon -e ts -w ./src -x npm run watch:serve",
>  "watch:serve": "node --loader ts-node/esm src/server.ts",
> ```

Using node 20 with sveltekit, this works

**Comment by JuYiYang** [comment]
> > if your tsconfig.json contains "module": "ESNext". I have used the below script in my package.json. It worked.
> > ```
> >  "start": "nodemon -e ts -w ./src -x npm run watch:serve",
> >  "watch:serve": "node --loader ts-node/esm src/server.ts",
> > ```
> 
> Using node 20 with sveltekit, this works



> > if your tsconfig.json contains "module": "ESNext". I have used the below script in my package.json. It worked.
> > ```
> >  "start": "nodemon -e ts -w ./src -x npm run watch:serve",
> >  "watch:serve": "node --loader ts-node/esm src/server.ts",
> > ```
> 
> Using node 20 with sveltekit, this works



> > if your tsconfig.json contains "module": "ESNext". I have used the below script in my package.json. It worked.
> > ```
> >  "start": "nodemon -e ts -w ./src -x npm run watch:serve",
> >  "watch:serve": "node --loader ts-node/esm src/server.ts",
> > ```
> 
> Using node 20 with sveltekit, this works



> > if your tsconfig.json contains "module": "ESNext". I have used the below script in my package.json. It worked.
> > ```
> >  "start": "nodemon -e ts -w ./src -x npm run watch:serve",
> >  "watch:serve": "node --loader ts-node/esm src/server.ts",
> > ```
> 
> Using node 20 with sveltekit, this works

Thank you😘

**Comment by jhonatanAlanFerreira** [comment]
I need `"type": "module"` in package.json
`npx tsx ./file.ts` worked for me

**Comment by quantuminformation** [comment]
same error in 2023

anyone code a tsx launch file for vscode that allows debugging?

**Comment by arsinclair** [comment]
If you suddenly started getting this issue, this might be the cause: https://github.com/TypeStrong/ts-node/issues/2094

**Comment by ejas404** [comment]
> Add this to the tsconfig.json:
> 
> ```
>   "compilerOptions": {
>     "esModuleInterop": true
>   }
> ```
> 
> and make sure to start the server with `ts-node`:
> 
> ```
> ts-node my_ts_node_server.ts
> ```
> 
> It is _crazy_ how hard it was for me to find this. This will allow you to use imports as well as use typescript.



> > Remove "type": "module" from package.json
> 
> If remove module type, you cannot use imports in your .ts files

for using esm add these 
 "compilerOptions": {
    

    "module": "CommonJS",                                
    "esModuleInterop": true,
                             
  }
  
  it worked for me 
  if you face importing .ts extension
  
  add this to your compilerOptions
   "allowImportingTsExtensions": true,
   
   Nb : Option 'allowImportingTsExtensions' can only be used when either 'noEmit' or 'emitDeclarationOnly' is set.ts 
   you have to set one of the true with it

**Comment by arsinclair** [comment]
> for using esm add these

> "module": "CommonJS",

That's not true. ESM and CJS (CommonJS) are two different things, changing `module` to `CommonJS` will make _tsc_ produce CommonJS code.

**Comment by jamesrr39** [comment]
I got this same error (`Unknown file extension ".ts"`), trying to run a typescript script with ts-node 10.9.1 and Node 20.10. I couldn't find a solution unfortunately (I tried `"esModuleInterop": true` in tsconfig), but running the script through [tsx](https://www.npmjs.com/package/tsx) worked, so I ended up migrating from ts-node to tsx.

I find it really odd that .ts files are not recognised by default. Surely ts-node should know how to handle .ts files?

**Comment by Rush** [comment]
This is what worked for me. Not even `ts-node-esm` worked.
```
node --experimental-specifier-resolution=node --loader ts-node/esm file.ts
```

Let me just say that the entire ESM situation in Node.JS is a catastrophe. It created so much pain, incompatibility, lost hours. I don't understand why some decisions were made that contributed to this pain. It's probably not as bad as Python2 and Python3 but very close!

**Comment by moneyDev1111** [comment]
for me worked the opposite ( updated node to the latest 21.x version )
the ts-node config part  in tsconfig.json
```json
"ts-node": {
		"esm": false,
		"compilerOptions": {
			"module": "NodeNext"
		}
	},
```

**Comment by eminoda** [comment]
tsconfig.json
````
{
  "compilerOptions": {
    "module": "ESNext", // tell tsc complier use esm module
    "moduleResolution": "Node10", // find file use CommonJS require
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "outDir": "dist"
  },
  "include": ["src/**/*"]
}
````
package.json

````
"type": "module",
````

**Comment by wen403** [comment]
try https://github.com/antfu/esno

**Comment by hellznrg** [comment]
> I got this same error (`Unknown file extension ".ts"`), trying to run a typescript script with ts-node 10.9.1 and Node 20.10. I couldn't find a solution unfortunately (I tried `"esModuleInterop": true` in tsconfig), but running the script through [tsx](https://www.npmjs.com/package/tsx) worked, so I ended up migrating from ts-node to tsx.
> 
> I find it really odd that .ts files are not recognised by default. Surely ts-node should know how to handle .ts files?

Switching to tsx was the only thing that worked for me. Now it's as simple as `yarn tsx .` and BOOM. Not sure what the problem with ts-node is. It's defintely a ts-node problem.
